name: Triggered by Repo B
on:
  repository_dispatch:
    types: [trigger-from-repo-b]
jobs:
  from-repo-b:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
      - name: Run Maven Tests
        run: mvn test
      - name: Confirm Trigger
        run: echo "Triggered by Repo B via repository_dispatch"
